### ISSUE TITLE
Releasing "Optional" Json Fields in 2.x

### ISSUE THREAD

**Issue by andylibrian** [coduo/php-matcher#106]
Can we release "optional" json fields in 2.x version? Maybe 2.3?
Apparently, it's not yet using php7 syntax.

Ref:
- https://github.com/coduo/php-matcher/issues/93
- https://github.com/coduo/php-matcher/pull/102
- https://github.com/coduo/php-matcher/commit/8cfa24bb381dc85771992000c448fc384ed5539a

**Comment by norzechowicz** [comment]
Here you go: https://github.com/coduo/php-matcher/pull/107

**Comment by andylibrian** [comment]
Awesome, thanks. Looking forward to merging and releasing.

**Comment by norzechowicz** [comment]
https://github.com/coduo/php-matcher/releases/tag/2.3.0
