### ISSUE TITLE
Version 2.3 is not compatible with php 5.3.0

### ISSUE THREAD

**Issue by Mateuszry** [coduo/php-matcher#108]
https://github.com/coduo/php-matcher/blob/79a27d13e0edc699ede6e64bcfee1e9bb5498793/src/Parser/ExpanderInitializer.php#L19-L33

The following code is not compatible with php version 5.3, because ::class is available in PHP 5.5.0
> The special ::class constant are available as of PHP 5.5.0, and allows for fully qualified class name resolution at compile, this is useful for namespaced classes:

Execute this code in lower PHP versions gives the following error:
> Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in ../vendor/coduo/php-matcher/src/Parser/ExpanderInitializer.php on line 19

**Comment by norzechowicz** [comment]
good catch, I forgot to update php version from >=5.3 into >=5.6, thanks!
