### ISSUE TITLE
Feature request: Assume array contains X elements

### ISSUE THREAD

**Issue by JarJak** [coduo/php-matcher#111]
Proposal: 
`@array@.count(5)` or `@array@.length(5)`, `@string@.length(5)`

**Comment by teklakct** [comment]
Can you provide some example use case where you want to use it? 
I can't imagine in what case it could be useful. 

Please consider that:

-  `@string@.length(5)` -> you can use a regexp pattern to check this
- `@array@.count(5)/length(5)` -> `$matcher->match(count($responseArray), 5);`

**Comment by JarJak** [comment]
How can I use `$matcher->match(count($responseArray), 5)` in behat tests?

**Comment by teklakct** [comment]
It doesn't matter where you use matcher. It could be a Behat feature context, PHPUnit test or your domain code.

You can decode JSON to array and  check if a specific value contains X elements. But I understand that you want to do easily match using this notation in JSON/XML pattern matcher.

It sounds good but I can't imagine when you must know how much items is in array. In most cases we only need to know about type.
Can you provide some live example?

**Comment by JarJak** [comment]
Simplest example would be if I want to test if limiting number of results in response works.

**Comment by teklakct** [comment]
@norzechowicz what do you think about that?

**Comment by norzechowicz** [comment]
Hmm but we already have [CountExpander](https://github.com/coduo/php-matcher/blob/master/src/Matcher/Pattern/Expander/Count.php) 🤔

**Comment by JarJak** [comment]
@norzechowicz how can I use CountExpander with JSON pattern matcher?

**Comment by JarJak** [comment]
@norzechowicz ok now I have found issue #90 so I have to use `"@array@.count(5)"` instead of `@array@.count(5)` to bypass the bug
