### ISSUE TITLE
Cannot mock Matcher 

### ISSUE THREAD

**Issue by Canadadry** [coduo/php-matcher#116]
I need to mock the main Matcher class which is marked as final. 

In order to do it I have made a fork and create an interface for matcher.

**Comment by teklakct** [comment]
`Matcher` class is marked as `final` for a reason. It is so simple that you **should** use it. I suggest you to check your code and **ensure** is everything is ok. In most cases your design is broken

**Comment by Canadadry** [comment]
Because I am building code arround the matcher and I need to test what happend when matcher failed or succeded. I could write some fake data but that sould not concerne my test. And your code is used as a service and therefore could be mock.
Anyway, I have forked it because `@uuid@` is missing some implementation. So I also use it to allow mocking.

**Comment by norzechowicz** [comment]
I think in this case we can remove final statement from Matcher

**Comment by teklakct** [comment]
Still not sure is that a good way to use it. I use `Matcher` like `if` construct in order to check some more complex conditions. 
IMO you don't need to mock `Matcher` but create some abstraction for it. You can create your own `Matcher` interface and mock it. Next create class which implements your interface and extends a coduo `Matcher`

BTW. Adding uuid pattern for `RegexConverter` looks interesting.

**Comment by Canadadry** [comment]
Yes it work too. It seems to me like adding another layer of abstraction only for mocking. Not very fan of this solution, but it does not require to fork the all project, which is a plus. 
I might go fir this solution if you add uuid pattern to RegexConverter.

I use this pattern in unit test of api with hateos implementation. Wich has a lot a autoreferencing link, with obviously a lot of uuid.

**Comment by teklakct** [comment]
@norzechowicz would you remove final statement from Matcher?

**Comment by norzechowicz** [comment]
I’m not sure, this final statement is so meaningless and creatig abstraction just to mock Matcher, sounds a bit like overengeneerig something simple. I would say, lets remove it

**Comment by Canadadry** [comment]
Before you anything, The removing the final statement is not enough to allow mocking, I had to do some other minor fix. You can have a lot at what I have on my fork. (From memory I gave also hadded an interface had make the factory return the interface)

For the exact use case here how Create my mock. 
```
 $simpleFactory = $this->getMockBuilder('Coduo\PHPMatcher\Factory\SimpleFactory')
            ->setMethods(['createMatcher'])
            ->getMock();
 $matcher = $this->getMockBuilder('Coduo\PHPMatcher\MatcherInterface')
            ->setMethods(['match','getError'])
            ->getMock();
 $simpleFactory->method('createMatcher')->willReturn($matcher);
 $matcher->method('match')->willReturn($matcherReturn);
 $matcher->method('getError')->willReturn('mock error');
```

Also one last thing, I have written the first version of this mock of your service montg ago, the issue  only  occured recently when you changed the interface.
