### ISSUE TITLE
The ArrayMatcher does not match inside an existing string

### ISSUE THREAD

**Issue by thomasbisignani** [coduo/php-matcher#136]
Hello,

The `ArrayMatcher` does not match inside an existing string. 
Examples with this following code : 
```php
$value = [
     'foo' => "http://foo.com/bar"
 ];

if (!PHPMatcher::match($value, $pattern, $error)) {
    echo $error;
} else {
    echo "Matched.";
}
```
**This pattern works** :
```php
$pattern = [
    'foo' =>  '@string@'
];
```
**Result**: 
`Matched.`

**This pattern does not work** : 
```php
$pattern = [
    'foo' =>  'http://foo.com/@string@'
];
```
**Result**: 
`"http://foo.com/bar" does not match "http://foo.com/@string@".`

**Comment by norzechowicz** [comment]
`http://foo.com/bar` should match `@string@.startsWith("http://foo.com/")`

**Comment by norzechowicz** [comment]
Agree, feel free to open PR! 🍻
