### ISSUE TITLE
Allow Date comparaison

### ISSUE THREAD

**Issue by Canadadry** [coduo/php-matcher#139]
Hello, 

I've been in the need of testing timestamp of token, if it was prior or after a certain datetime. I've looked at how symfomy constraint allow to validate date. 

They let us use two main objects : 

- One type validator => [https://symfony.com/doc/current/reference/constraints/DateTime.html](url) something we already have with `"@string@.isDateTime()"`
- Severals "Comparaison constraint" we also have those, but (_which if I am not mistaken_) only work for number. In symfony they work for both number and datetime see this one for example => [https://symfony.com/doc/current/reference/constraints/LessThan.html](url) 

I think it would be nice if we add the same kind of functionality. It would only require to write or adapt a few expanders. 

I'll try to PR something today or this week, in the mean time what do you think about it ? Have you any suggestion?

**Comment by norzechowicz** [comment]
closed by #141
