### ISSUE TITLE
Issue with TextMatcher registration.

### ISSUE THREAD

**Issue by bendavies** [coduo/php-matcher#142]
Hey there,

Think I've encounter an issue with the default matcher chain where this doesn't work:

```php
<?php

declare(strict_types=1);

use Coduo\PHPMatcher\PHPMatcher;

include_once 'vendor/autoload.php';

$value = '{"foo" : "/accounts/9a7dae2d-d135-4bd7-b202-b3e7e91aaecd"}';
$pattern = '{"foo" : "/accounts/@uuid@"}';
$error = '';

var_dump(PHPMatcher::match($value, $pattern, $error));
var_dump($error);
```

This should work if i'm not missing something obvious!
I can't see exactly how to fix it, sorry.
Cheers!

**Comment by norzechowicz** [comment]
fixed, thanks for reporting and sorry for long time without any response

**Comment by bendavies** [comment]
thanks!
