### ISSUE TITLE
Packagist not auto-updated

### ISSUE THREAD

**Issue by MichaelKubovic** [coduo/php-matcher#147]
Hey, would be nice if you could setup git hook to let packagist know whenever you release a new version. Currently 3.1.2 is not listed on packagist despite it's been relased on github 11 days ago.

More info can be found on https://packagist.org/about

Thanks!

**Comment by norzechowicz** [comment]
Right, it was using legacy hooks, should be fine now! 
![image](https://user-images.githubusercontent.com/1921950/53041741-0a52bd00-3485-11e9-8941-7cf52bb84d84.png)
Thanks for heads up!
