### ISSUE TITLE
Example code fail

### ISSUE THREAD

**Issue by hpatoio** [coduo/php-matcher#156]
I've issue with the code in the example. I create this very simple script.

```
#!/usr/bin/env php
<?php
// application.php

use Coduo\PHPMatcher\Factory\SimpleFactory;

require __DIR__.'/vendor/autoload.php';

$factory = new SimpleFactory();
$matcher = $factory->createMatcher();

$matcher->match($value = '{"foo": "bar"}', $pattern = '{"foo": "@string@"}');
echo $matcher->getError();
```
but I get : `Any matcher from chain can't match value "{"foo": "bar"}" to pattern "{"foo": "@string@"}"`

I'm using latest version of this library and version `7.3.7` of PHP 

Can't understand where I go wrong.

**Comment by norzechowicz** [comment]
hey @hpatoio I sorry to hear that this does not work for you, in fact this is another report about php matcher not working on php 7.3 when in the same time our testsuite is passing at travis https://travis-ci.org/coduo/php-matcher/jobs/556500337

Could you maybe list modules you have installed and make sure you have latest version of php-matcher? Does this problem also occurs at master branch?

**Comment by norzechowicz** [comment]
I will reopen this is you will get back to me with some answers

**Comment by norzechowicz** [comment]
Actually I was able to understand and fix this issue thanks to @teklakct
