### ISSUE TITLE
Array repeat expander not working 

### ISSUE THREAD

**Issue by Linkinou** [coduo/php-matcher#157]
Hello there,

I'm trying to understand how to work with array repeat expander.

I tried to match this :
```JSON
 [
     {
         "label": "Hello world !"
     }
 ]
```

with this : 
```JSON
'@array@.repeat({\"label\": \"@string@\"})'
```

but got this : 

```JSON
Type pattern "@array@" is not supported by TextMatcher.
```

Am I missing something ? 

I'm using PHP 7.1 and coduo/php-matcher 3.1

**Comment by teklakct** [comment]
First please start read errors ;)
"Type pattern "@array@" is not supported by TextMatcher." You're using a TextMatcher which obviously matches text, not arrays. For this what you need try to use JsonMatcher.
Note that the pattern should be wrapped in quotes.

```php
$value = '[{"label": "Hello world !"}]';
$pattern = '"@array@.repeat({\"label\": \"@string@\"})"';

$matcher->match($value, $pattern);
```

**Comment by Linkinou** [comment]
Thank you @teklakct 
Actually I was using the SimpleFactory thinking that it will give me a JsonMatcher automatically (based on the given value). 

So I guess I have to create a JsonMatcher like here ? https://github.com/coduo/php-matcher/blob/master/tests/Matcher/JsonMatcherTest.php#L19
