### ISSUE TITLE
Bug while comparing floats

### ISSUE THREAD

**Issue by SSMellow** [coduo/php-matcher#158]
While comparing two arrays, and in both there is same float value, matcher does not match. 
F.E. $payload1 = ['number' => 123.45, 'key' => 'random']
$payload2 = ['number' => 123.45, 'key' => 'random']

Error - "123.45" does not match "123.45". (Exception)

**Comment by teklakct** [comment]
I can't reproduce this. @SSMellow please provide a full working code example

**Comment by norzechowicz** [comment]
Closing since I wasn't able to reproduce it as well. @SSMellow please open a PR with failing tests case for this issue, then we will try to help you
