### ISSUE TITLE
can we  check key exisitence ?

### ISSUE THREAD

**Issue by videni** [coduo/php-matcher#181]
example 

```json
{
    "data": {
        "createUserFormSchema":  {
            "formData": "@json@",
            "schema": "@json@",
            "uiSchema": "@json@"
        }
    }
}

```

 I only want to check the exisitence  of the keys, formData, schema, uiSchema .

**Comment by norzechowicz** [comment]
hey @videni indeed this one was still missing, I just added it in #185 
it will be released in version 4.0 that is coming soon!
