### ISSUE TITLE
JsonMatcher does not support JSON pattern including another pattern in the middle of a string value

### ISSUE THREAD

**Issue by julienfalque** [coduo/php-matcher#183]
With the following pattern:
```
{
    "foo": "/foo/@uuid@/bar"
}
```
`JsonMatcher` will not match anything because its `canMatch()` method returns `false`.

This seems to be caused by `Json::transformPattern()` that changes the pattern to:
```
{
    "foo": "/foo/"@uuid@"/bar"
}
```
which is not valid JSON (notice the added quotes in the value).

**Comment by norzechowicz** [comment]
Hmm, weird. I just checked your example using [Pattern Matcher Sandbox](https://pattern-matcher.azurewebsites.net/?form%5Bvalue%5D=%7B%0D%0A++++%22foo%22%3A+%22%2Ffoo%2Fbf5792af-60f2-4584-9166-d235ce75e240%2Fbar%22%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++++%22foo%22%3A+%22%2Ffoo%2F%40uuid%40%2Fbar%22%0D%0A%7D&form%5Bmatch%5D=) and it seems to be working just fine? Which version of php-matcher you are using?

**Comment by julienfalque** [comment]
3.2.2.

**Comment by norzechowicz** [comment]
It's exactly the same version that Pattern Matcher Sandbox is using, weird... Could you maybe open a pull request with a failing test for this scenario?

**Comment by julienfalque** [comment]
See #187.
