### ISSUE TITLE
@...@ is greedy

### ISSUE THREAD

**Issue by julienfalque** [coduo/php-matcher#194]
Currently the `@...@` pattern seems to be greedy, so if we use it in e.g. the beginning of an array, anything that comes after it in the pattern isn't actually validated.

For example:
```json
{
    "foo": [
        "@...@",
        "some value"
    ]
}
```
If the last element of the `"foo"` array isn't `"some value"`, the pattern matches anyway.

This also applies to property values, for example:
```json
{
    "foo": "@...@",
    "bar": "some value"
}
```
the pattern still matches whatever the actual value of the `"bar"` property is.

Is it possible to make the `@...@` pattern lazy instead of greedy?

**Comment by norberttech** [comment]
Hey, could you create an example of pattern and value that you mentioned above using https://php-matcher.norbert.tech and share the url to this example with us here?

**Comment by julienfalque** [comment]
Yep: see [example 1](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++++%22foo%22%3A+%5B%0D%0A++++++++%22foo%22%2C%0D%0A++++++++%22not+bar%22%0D%0A++++%5D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++++%22foo%22%3A+%5B%0D%0A++++++++%22%40...%40%22%2C%0D%0A++++++++%22bar%22%0D%0A++++%5D%0D%0A%7D&form%5Bmatch%5D=) and [example 2](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++++%22foo%22%3A+%22foo%22%2C%0D%0A++++%22bar%22%3A+%22not+bar%22%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++++%22foo%22%3A+%22%40...%40%22%2C%0D%0A++++%22bar%22%3A+%22bar%22%0D%0A%7D&form%5Bmatch%5D=)

**Comment by norberttech** [comment]
This is not a bug, `@...@` represents array unbounded pattern, meaning that matcher ignores anything after it including the value which is at the same position as unbounded pattern. 

If you want to skip just certain elements use [@*@](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++++%22foo%22%3A+%5B%0D%0A++++++++%22foo%22%2C%0D%0A++++++++%22not+bar%22%0D%0A++++%5D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++++%22foo%22%3A+%5B%0D%0A++++++++%22%40*%40%22%2C%0D%0A++++++++%22bar%22%0D%0A++++%5D%0D%0A%7D&form%5Bmatch%5D=) aka universal key

**Comment by julienfalque** [comment]
My use case was not to skip a certain element but to match a specific value at the end of an array, no matter what the array contains *before* that element. In the example in the first post above, the pattern would match
```json
{
    "foo": [
        "some value"
    ]
}
```
or
```json
{
    "foo": [
        "foo",
        "bar",
        "some value"
    ]
}
```
but not
```json
{
    "foo": [
        "foo",
        "bar"
    ]
}
```

**Comment by norberttech** [comment]
matching the last element of array is not supported unless you are aware of the array size, for example, if you know that array has 5 elements and only want to match the last on you can use:
```
[
    "@*@",
    "@*@",
    "@*@",
    "@*@",
    "something"         
]
```

It's not the ideal solution but I don't see any better alternative for now. 

The role of `@...@` is to skip all further elements from matching, meaning that if you put any other pattern after `@...@` it will also be skipped. 

This however does not mean that `@...@` is broken but that different matcher that would let you match a specific value in the array is missing.
