### ISSUE TITLE
An error if it does not match the pattern

### ISSUE THREAD

**Issue by grn-it** [coduo/php-matcher#198]
An error occurs while executing this code:
```
$this->assertMatchesPattern(['key' => '@string@'], ['key' => 1]);
```

```
Error: Call to undefined method Coduo\PHPMatcher\PHPUnit\PHPMatcherConstraint::exporter()

/srv/api/vendor/coduo/php-matcher/src/PHPUnit/PHPMatcherConstraint.php:47
/srv/api/vendor/coduo/php-matcher/src/PHPUnit/PHPMatcherConstraint.php:89
/srv/api/vendor/coduo/php-matcher/src/PHPUnit/PHPMatcherAssertions.php:13
```

version:
```
coduo/php-matcher                        4.0.0   PHP Matcher enables you to...
coduo/php-to-string                      3.0.0   Simple library that conver...
```

**To fix this error, you need to fix this line of code**
vendor/coduo/php-matcher/src/PHPUnit/PHPMatcherConstraint.php::47
Before:
```
. "\nPattern: " . $this->exporter()->export($this->pattern)
```
After:
```
. "\nPattern: " . $this->exporter->export($this->pattern)
```
Because the exporter() method does not exist

Thanks for the great library! :)

**Comment by grn-it** [comment]
This problem appears in phpunit version 7.5.20
Method exporter() not exist in https://github.com/sebastianbergmann/phpunit/blob/7.5.20/src/Framework/Constraint/Constraint.php

But in phpunit 8.0 method has been added https://github.com/sebastianbergmann/phpunit/blob/8.0.0/src/Framework/Constraint/Constraint.php

**Comment by sjuvonen** [comment]
@grn-it Assuming that you're running Symfony, you need to specify the correct PHPUnit version in phpunit.xml(.dist). By default Symfony will want to install PHPUnit 7.5.
