### ISSUE TITLE
Not able to match @null@||@array@

### ISSUE THREAD

**Issue by maciej-sz** [coduo/php-matcher#212]
The case is that I am matching optional array, which can be NULL.

A little modified example form `php-matcher.norbert.tech` ([link](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++%22users%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22firstName%22%3A+%22Norbert%22%2C%0D%0A++++++%22lastName%22%3A+%22Orzechowicz%22%2C%0D%0A++++++%22title%22%3A+%22Software+Architect%22%2C%0D%0A++++++%22created%22%3A+%222014-01-01%22%2C%0D%0A++++++%22roles%22%3A%5B%22ROLE_USER%22%2C+%22ROLE_DEVELOPER%22%5D%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++%22users%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22firstName%22%3A+%22%40string%40%22%2C%0D%0A++++++%22lastName%22%3A+%22%40string%40%22%2C%0D%0A++++++%22title%22%3A+%22%40string%40%22%2C%0D%0A++++++%22created%22%3A+%22%40string%40.isDateTime%28%29%22%2C%0D%0A++++++%22roles%22%3A+%22%40null%40%7C%7C%40array%40%22%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D&form%5Bmatch%5D=)):
```
{
  "users": [
    {
      "firstName": "@string@",
      "lastName": "@string@",
      "title": "@string@",
      "created": "@string@.isDateTime()",
      "roles": "@null@||@array@"
    }
  ]
}
```

and the output contains:

`#162 Matcher Coduo\PHPMatcher\Matcher\ScalarMatcher error: "Array(2)" does not match "@array@".`

**Comment by norberttech** [comment]
This one was fixed by @mtomala and released:
https://github.com/coduo/php-matcher/releases/tag/5.0.1
https://github.com/coduo/php-matcher/releases/tag/4.0.2

Thanks again @mtomala !
