### ISSUE TITLE
Confusing error message 

### ISSUE THREAD

**Issue by alexsegura** [coduo/php-matcher#227]
Hi. 

Thank you for making PHP Matcher 🙂 

With a PHP Matcher expectation like this:

```json
{
  "@context":"/api/contexts/ConstraintViolationList",
  "@type":"ConstraintViolationList",
  "hydra:title":"An error occurred",
  "hydra:description":@string@,
  "violations":[
    {
      "propertyPath":"total",
      "message":@string@,
      "code":""
    }
  ]
}
```

If `[violations][0][code]` is `null` null, PHP Matcher gives the following message 

> Value "" does not match pattern "" at path: "[violations][0][code]"

This is confusing, when seeing this you wonder why `"" !== ""` 🤔 

---

Maybe it could be instead: 

> Value null does not match pattern "" at path: "[violations][0][code]"

**Comment by norberttech** [comment]
could you please create an example https://php-matcher.norbert.tech/ and share the URL here so I can replicate this issue?

**Comment by alexsegura** [comment]
[Here it is](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++%22users%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22firstName%22%3A+%22%22%2C%0D%0A++++++%22lastName%22%3A+%22Orzechowicz%22%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++%22users%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22firstName%22%3A+null%2C%0D%0A++++++%22lastName%22%3A+%22%40string%40%22%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D&form%5Bmatch%5D=)

**Comment by gabrielanhaia** [comment]
@alexsegura I was just wondering why haven't used `@null@` as in the documentation?

If you do so as for the other kind of validations, the error will be more clear: [LIKE HERE](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++%22users%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22firstName%22%3A+%22%22%2C%0D%0A++++++%22lastName%22%3A+%22Orzechowicz%22%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++%22users%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22firstName%22%3A+%22%40null%40%22%2C%0D%0A++++++%22lastName%22%3A+%22%40string%40%22%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D&form%5Bmatch%5D=)
