### ISSUE TITLE
How does the `.inArray()` pattern expander work ?

### ISSUE THREAD

**Issue by wijourdil** [coduo/php-matcher#296]
Hi,

I have an issue, I don't know how to use the `.inArray()` pattern expander.
Whatever I try, I get this error message : 
```
MyTest::test_something
Failed asserting that Value "my-string" does not match pattern "@string@.inArray([])" at path: "[0][id]".

/.../my-project/vendor/coduo/php-matcher/src/PHPUnit/PHPMatcherConstraint.php:65
/.../my-project/vendor/coduo/php-matcher/src/PHPUnit/PHPMatcherAssertions.php:21
/.../my-project/tests/MyTest.php:35
```

I'm using the `assertMatchedPattern()` trait method, and the pattern I use is this : 
(I try with an empty array, but I also tried with hardcoded array or "json-encoded" variables)
```php
[
    'id' => "@string@.inArray([])",
    'name' => "@string@.isNotEmpty()",
]
```

---

According to what I saw in the `InArray` expander class, I should have one of these error messages : 
```
InArray expander require "array", got "%s".
```
or
```
%s doesn't have \"%s\" element.
```

Am I using it wrong ? Is it possible to add an example in the documentation ? Thanks a lot  ! 🙏

**Comment by wijourdil** [comment]
I think I have understood my mistake.

Is this pattern expander supposed to check if a string is contained in a given array, or to check if an array contains a given string ?

**Comment by norberttech** [comment]
Hey, yeah now when I look at it, inArray expander is not as self descriptive as I thought originally, I will adjust the documentation with proper example but in the meantime please find it here: [@array@.inArray() example](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++%22users%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22roles%22%3A%5B%22ROLE_USER%22%2C+%22ROLE_DEVELOPER%22%5D%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++%22users%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22roles%22%3A+%22%40array%40.inArray%28%5C%22ROLE_USER%5C%22%29%22%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D&form%5Bmatch%5D=)

**Comment by norberttech** [comment]
I'm closing this one, in case of any more questions, feel free to open new issues. I also updated readme with an example of inArray
