### ISSUE TITLE
Expecting null but give an array throws strange runtime error

### ISSUE THREAD

**Issue by alexander-schranz** [coduo/php-matcher#334]
I have the following snapshot:

```json
{
    "availableLocales": null
}
```

Which is testing the following json:

```json
{
    "availableLocales": [
        "en"
    ]
}
```

Example: 
https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++++%22availableLocales%22%3A+%5B%0D%0A++++++++%22en%22%0D%0A++++%5D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++++%22availableLocales%22%3A+null%0D%0A%7D&form%5Bmatch%5D=

It errors with Argument 4 is null instead of string at:

https://github.com/coduo/php-matcher/blob/ac729bb75e5ebf899d6048695fbf782e83e043b1/src/Matcher/ArrayMatcher.php#L76

It seems like a problem with expecting null but getting an array but not sure where the error exists.

**Comment by norberttech** [comment]
hey @alexander-schranz thanks for reporting this bug! 
https://github.com/coduo/php-matcher/pull/336 will fix it, expect a new patch release soon!

**Comment by norberttech** [comment]
Version 6.0.8 was just released

**Comment by alexander-schranz** [comment]
@norberttech Thank you!
