### ISSUE TITLE
Multiple elements JSON matching

### ISSUE THREAD

**Issue by piotrjura** [coduo/php-matcher#35]
Given I have a JSON response witch returns an array of 10 elements, like:

``` json
[
      {
        "id": 1,
        "name": "Posiłek @integer@",
        "date": @string@
      },
      {
        "id": 2,
        "name": "Posiłek @integer@",
        "date": @string@
      },
      {
        "id": 3,
        "name": "Posiłek @integer@",
        "date": @string@
      },
      @repeat@
]
```

I'd like to point somehow that there's one unique pattern which should be matched 10 times in JSON response, becouse array has 10 items. Are you thinking about such feature?

**Comment by gitis** [comment]
+1

**Comment by sorpion** [comment]
+1

**Comment by ZilKil** [comment]
+1

**Comment by tompoc** [comment]
+1

**Comment by norzechowicz** [comment]
@gitis @sorpion @ZilKil @tompoc I think we all agree that this feature would be extremely useful, any of you is more than welcome to create a pull request. Unfortunately I simply don't have time to do it on my own, but don't hesitate to ask for any help you need.
