### ISSUE TITLE
Consider upgrade doctrine/lexer to 2.x branch

### ISSUE THREAD

**Issue by jdecool** [coduo/php-matcher#457]
There's two new major branch of `doctrine/lexer`.

We can consider to switch to 2.0 branch as its dependencies do not result in BC.

Currently we can have issue installing php-matcher with some recent dependencies which are not compatible with `doctrine/lexer` 1 (I think about latest version of `friendsofphp/php-cs-fixer`).

**Comment by norberttech** [comment]
If possible, I think I would like to support `doctrine/lexer: ^1||^2` versions, if not `^2` can go to 6.x as it will be anyway released as 6.1.0

**Comment by norberttech** [comment]
https://github.com/coduo/php-matcher/pull/458

**Comment by jdecool** [comment]
Great! 

Thanks
