### ISSUE TITLE
Json array of object compare

### ISSUE THREAD

**Issue by marglix** [coduo/php-matcher#460]
Hi, I have one problem with json. I want compare some json array regardless of the order. For example:
`
[
    {
        "name": "some_name"
    },
    {
        "name": "some_another_name"
    }
],
`
and
`
[
    {
        "name": "some_another_name"
    },
    {
        "name": "some_name"
    }
],
`

**Comment by norberttech** [comment]
Technically speaking it is possible through pattern expanders, it might not be the easiest one to build but combination of hasProperty(), isNotEmpty(), inArray() and oneOf() should do the trick
