### ISSUE TITLE
When new release with PHP Unit support?

### ISSUE THREAD

**Issue by Aerendir** [coduo/php-matcher#462]
Hello dear team,
I'm writing just to know if there is an ETA for the release of a new version with support for PHPUnit 10.

I saw there was a PR that implemented it (https://github.com/coduo/php-matcher/pull/456) and it is also already merged.

I know maintain a package is a hard work, so this is not to put pressure on you.

It is simply a question the answer of which permits me to understand how much time I could expect before upgrading (as upgrading to PHPUnit is not so immediate) and plan it better.

Thank you in advance for the reply and many than you for the great work you did (and still do) with this library!

**Comment by norberttech** [comment]
hey @Aerendir! Sorry, I totally forgot to create new release with latest changes 🤦 
Here you go, [6.0.12](https://github.com/coduo/php-matcher/releases/tag/6.0.12)
