### ISSUE TITLE
Release 6.0.12 not longer compatible with PHPUnit 9

### ISSUE THREAD

**Issue by alexander-schranz** [coduo/php-matcher#463]
With the new release of php-matcher there seems to be incompatibility added to PHPUnit 9:

```
PHP Fatal error:  Declaration of Coduo\PHPMatcher\PHPUnit\PHPMatcherConstraint::fail(
mixed $other, string $description, ?SebastianBergmann\Comparator\ComparisonFailure $comparisonFailure = null
): never

must be compatible with

PHPUnit\Framework\Constraint\Constraint::fail(
$other, $description, ?SebastianBergmann\Comparator\ComparisonFailure $comparisonFailure = null
): void
in /home/runner/work/SuluContentBundle/SuluContentBundle/vendor/coduo/php-matcher/src/PHPUnit/PHPMatcherConstraint.php on line 61
 ```
 
There should no Parameter `Types` added to the `PHPMatcherConstraint` they currently break the functionality. Only `Return Types` should had added to the `PHPMatcherConstraint` to make it compatible with PHPUnit 10.

**Comment by oldcodefork** [comment]
@alexander-schranz I made a [fork](https://packagist.org/packages/oldcodefork/coduo-php-matcher) to get back PHPUnit 9 compatibility.
