### ISSUE TITLE
Using @string@ in JSON response

### ISSUE THREAD

**Issue by inanzzz** [coduo/php-matcher#47]
Hi,

Since `batch1064` always differs I would like to replace it with `@string@` but when I do that tests still fail.

I'm using Symfony2 and have run `composer require --dev "coduo/php-matcher"` and all went fine. Apart from replacing `batch1064` with `@string@`, what else should I do? E.g. I'm seeing two lines below as standard but where do I put them? Somewhere in FeatureContext.php, maybe?

`@Then /^(?:the )?response should contain json:$/` is a build-in method in [WebApiContext.php](https://github.com/Behat/CommonContexts/blob/master/Behat/CommonContexts/WebApiContext.php#L182) of Behat.

```
$factory = new SimpleFactory();
$matcher = $factory->createMatcher();
```

MY EXAMPLE
```
  Scenario: Whatever whatever
    When I send a GET request to "/1/products?id=1"
    Then the response should contain json:
    """
    {
      "products": [
        {
          "name": "Aaaa",
          "images": [
            {
              "type": "url",
              "value": "http:\/\/www.abc.com\/imagegallery\/batch1064\/image.JPG"
            }
          ]
        }
      ]
    }
    """
```

**Comment by javierseixas** [comment]
I think you should use the `TextMatcher` for that case. You'll need to implement php-matcher into Behat. Take a look into this repository: https://github.com/jakzal/RestExtension to get an example. Sorry I cannot give a deep explanation right now. I'll try to do it soon.

**Comment by inanzzz** [comment]
Thanks for the info. I decided to use Behat's native placeholder option so it's fine now.

**Comment by norzechowicz** [comment]
This is why I dont like behat extensions that adds "universal" steps.
Anyway you can just simply create a step in your feature:
```Then json response should match:```

which should alllow you to generate following method in your Context class. 

```php
    /**
     * @Then json response should match:
     */
    public function jsonResponseShouldMatch(PyStringNode $jsonPattern)
    {
        $matcher = (new SimpleFactory())->createMatcher();

        if (!$matcher->match($this->getSession()->getPage()->getContent(), (string) $jsonPattern)) {
            throw new \RuntimeException($matcher->getError());
        }
    }
```

P.S. sorry for my late response

**Comment by inanzzz** [comment]
@norzechowicz - I'll take a note of your example too along with matcher option for future references so thank you for the response.
