### ISSUE TITLE
Not able to match `@null@||@array@` (again)

### ISSUE THREAD

**Issue by Aerendir** [coduo/php-matcher#471]
There is already a closed issue that reports my same exact problem:

- https://github.com/coduo/php-matcher/issues/212

My array structure is almost this:

```json
{
    "@context": "\/api\/contexts\/MyClass",
    "@id": "\/api\/myclasses\/2",
    "hydra:member": [
        {
            "id": 1,
            "my_key": {
                "key1": "EUR",
                "key2": 0.22
            }
        }
    ]
}
```

`my_key` can also be `null`:

```json
{
    "@context": "\/api\/contexts\/MyClass",
    "@id": "\/api\/myclasses\/2",
    "hydra:member": [
        {
            "id": 1,
            "my_key": null
        }
    ]
}
```

So, to validate this structure, I use this pattern:

```
[
                '@context'         => '/{app_api_entrypoint}/contexts/' . StringHelper::getClassBaseName(Item::class),
                '@id'              => '/{app_api_entrypoint}{api_endpoint}',
                '@type'            => 'hydra:Collection',
                'hydra:totalItems' => AbstractItemsFixture::COUNT_TOTAL_IN_ACCOUNT,
                'hydra:member'     => [
                    [
                        '@id' => '@string@',
                        'my_key' => '@array@ || @null@',
...
```

This validation does not pass:

> Failed asserting that Value "Array(2)" does not match pattern "[hydra:member][0]" at path: "[hydra:member][0][my_key]".

Am I doing it wrong or is it actually a bug?

**Comment by norberttech** [comment]
Hey @Aerendir it [looks like a bug](https://php-matcher.norbert.tech/?form%5Bvalue%5D=%7B%0D%0A++++%22%40context%22%3A+%22%5C%2Fapi%5C%2Fcontexts%5C%2FMyClass%22%2C%0D%0A++++%22%40id%22%3A+%22%5C%2Fapi%5C%2Fmyclasses%5C%2F2%22%2C%0D%0A++++%22hydra%3Amember%22%3A+%5B%0D%0A++++++++%7B%0D%0A++++++++++++%22id%22%3A+1%2C%0D%0A++++++++++++%22my_key%22%3A+%7B%0D%0A++++++++++++++++%22key1%22%3A+%22EUR%22%2C%0D%0A++++++++++++++++%22key2%22%3A+0.22%0D%0A++++++++++++%7D%0D%0A++++++++%7D%0D%0A++++%5D%0D%0A%7D&form%5Bpattern%5D=%7B%0D%0A++++%22%40context%22%3A+%22%5C%2Fapi%5C%2Fcontexts%5C%2FMyClass%22%2C%0D%0A++++%22%40id%22%3A+%22%5C%2Fapi%5C%2Fmyclasses%5C%2F2%22%2C%0D%0A++++%22hydra%3Amember%22%3A+%5B%0D%0A++++++++%7B%0D%0A++++++++++++%22id%22%3A+1%2C%0D%0A++++++++++++%22my_key%22%3A+%22%40null%40%7C%7C%40array%40%22%0D%0A++++++++%7D%0D%0A++++%5D%0D%0A%7D&form%5Bmatch%5D=). It seems that or condition is not handled properly and it's failing whenever the first check fails.

**Comment by Aerendir** [comment]
I don't know... I tried to debug, but I'm not so used to the library, so I didn't had a good result...

Anyway, the live sandbox is very useful!

You should put it in a template for GitHub when opening a bug issue, asking to reproduce the problem...

**Comment by norberttech** [comment]
> You should put it in a template for GitHub when opening a bug issue, asking to reproduce the problem...

[Done!](https://github.com/coduo/php-matcher/issues/new/choose)

**Comment by GeLoLabs** [comment]
The issue comes from the "MatcherFactory", it builds an "ArrayMatcher" which uses an "OrMatcher" which don't use any "ArrayMatcher" in its chain and so this "OrMatcher" (which is different from the one used by the main matcher) is not able to match "@array@" (see https://github.com/coduo/php-matcher/blob/6.x/src/Factory/MatcherFactory.php#L52)
