### ISSUE TITLE
Consider adding support for doctrine/lexer 3

### ISSUE THREAD

**Issue by Guuzen** [coduo/php-matcher#473]
For now, it is not supported.
It prevents doctrine/orm package from being upgraded because it [requires](https://github.com/doctrine/orm/blob/95da667862eeb1f94f3b09b2ebc708cfd929f5fe/composer.json#L32C10-L32C32) doctrine/lexer 3 and higher.

**Comment by norberttech** [comment]
Hey, yes I’m aware of this limitation, in fact, I even tried to upgrade but keeping support for all the versions seems to be a bit problematic due to bc breaks in the lexer.
Instead, I think we might want to drop doctrine lexer and look into something that does not put constraints on things like Dbal/ORM 

https://github.com/phplrt/phplrt seems to be a nice alternative

**Comment by Guuzen** [comment]
> but keeping support for all the versions seems to be a bit problematic due to bc breaks in the lexer.

Is there any reason to keep the support of the old versions of doctrine/lexer? Maybe there are other advantages of replacing the dependency? :thinking:

**Comment by norberttech** [comment]
honestly, the only reason is that I don't want php-matcher to force upgrades of orm/dbal at all projects that are using it. I would also prefer to detach from doctrine in general, not because it's bad, but because it's coupled with orm/dbal

**Comment by jkobus** [comment]
I think this is the reason I am unable to install it in a project with symfony 6.4:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - coduo/php-matcher[v1.0.0, ..., 1.1.8] require symfony/property-access ~2.3 -> found symfony/property-access[v2.3.0, ..., v2.8.52] but the package is fixed to v6.4.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - coduo/php-matcher[2.0.0, ..., 2.4.0] require symfony/property-access ^2.3|^3.0 -> found symfony/property-access[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but the package is fixed to v6.4.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - coduo/php-matcher[3.0.0, ..., 3.2.3] require symfony/property-access ^2.3|^3.0|^4.0 -> found symfony/property-access[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44] but the package is fixed to v6.4.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - coduo/php-matcher[4.0.0, ..., 4.0.2] require symfony/property-access ^2.3|^3.0|^4.0|^5.0 -> found symfony/property-access[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.38] but the package is fixed to v6.4.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - coduo/php-matcher[5.0.0, ..., 5.0.1, 6.0.0, ..., 6.0.10] require doctrine/lexer ^1.0 -> found doctrine/lexer[v1.0, ..., 1.2.3] but the package is fixed to 3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - coduo/php-matcher[6.0.11, ..., 6.0.14] require doctrine/lexer ^1.0||^2.0 -> found doctrine/lexer[v1.0, ..., 1.2.3, 2.0.0, 2.1.0, 2.1.1] but the package is fixed to 3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires coduo/php-matcher * -> satisfiable by coduo/php-matcher[v1.0.0, ..., 1.1.8, 2.0.0, ..., 2.4.0, 3.0.0, ..., 3.2.3, 4.0.0, 4.0.1, 4.0.2, 5.0.0, 5.0.1, 6.0.0, ..., 6.0.14].


```

```
composer why doctrine/lexer 
doctrine/orm                    3.1.0  requires  doctrine/lexer (^3)           
egulias/email-validator         4.0.2  requires  doctrine/lexer (^2.0 || ^3.0) 
scienta/doctrine-json-functions 6.0.0  requires  doctrine/lexer (^2.0 || ^3.0) 
symfony/doctrine-bridge         v6.4.5 conflicts doctrine/lexer (<1.1)         
symfony/validator               v6.4.4 conflicts doctrine/lexer (<1.1) 
```

Downgrading to:
`composer require doctrine/orm:^2`

... seems to work for now.

**Comment by norberttech** [comment]
hmm maybe as an intermediate step, we should actually upgrade lexer to ^3.0 🤔 I'm a bit busy currently but if anyone would like to bump it to 3.0 we could merge it and release I believe without a new version since it's not a BC break (meaning it can't break anyone code because composer would prevent update)

**Comment by norberttech** [comment]
resolved by https://github.com/coduo/php-matcher/pull/477

**Comment by adam-marchewicz-tg** [comment]
@norberttech any idea when the new version of `php-matcher` will be released?

**Comment by norberttech** [comment]
> @norberttech any idea when the new version of `php-matcher` will be released?

hey, sorry for the daly, I was waiting for another PR to get merged. I still need to resolve some tools dependencies conflicts but I believe I should be able to push new release later today

**Comment by adam-marchewicz-tg** [comment]
Thanks for the quick response. Sounds great!
