### ISSUE TITLE
The branch 6.0 is out of date but composer will provide it as it think its latest dev version

### ISSUE THREAD

**Issue by alexander-schranz** [coduo/php-matcher#496]
**Describe the bug**

The branch 6.0 is out of date but composer will provide it as it think its latest version

**To Reproduce**

```
composer require coduo/php-matcher:"^6.0.16"
```

```
composer config minimum-stability dev
```

```
composer update
```

It installs the `6.0-dev` branch which does not contain all fixes: https://github.com/coduo/php-matcher/compare/6.0...6.0.16

**Expected behavior**

There are solutions remove the 6.0 branch keep onlx the 6.x branch, or update the 6.0 branch with latest changes of 6.0.16 or other fixes.

**Screenshots**

https://github.com/sulu/sulu/actions/runs/11842548301/job/33001403218?pr=7653

Following thing was fixed but because outdated 6.0 branch still get the error on testing dev versions:

![Bildschirmfoto 2024-11-14 um 19 18 06](https://github.com/user-attachments/assets/6e1c18cb-0db6-41e8-879d-6507f6da84d0)

**Additional context**

**Comment by norberttech** [comment]
Nice catch! Let me remove the branch 6.0 and keep 6.x for now. 
6.0 will come back once we start working on 7.x features

**Comment by alexander-schranz** [comment]
Thank you can you check if you can manually update packagist here:

https://packagist.org/packages/coduo/php-matcher#6.0.x-dev

Or may remove the 6.0.x it still on packagist else available:

![Bildschirmfoto 2024-11-15 um 08 48 05](https://github.com/user-attachments/assets/04f19c8b-35d7-41c2-b478-3845abbec568)

**Comment by norberttech** [comment]
yes, sorry I missed that one, should be fine now 
<img width="474" alt="image" src="https://github.com/user-attachments/assets/8f4c98c8-bcf5-4406-8c6d-5eeb6922a1b6">

**Comment by alexander-schranz** [comment]
Thx works now 👍
