### ISSUE TITLE
Support more characters on TextMatcher

### ISSUE THREAD

**Issue by yosmanyga** [coduo/php-matcher#52]
It would be nice to allow more characters on text matcher. Currently is not possible to match as string a text with characters with accents.

**Comment by norzechowicz** [comment]
Hello @yosmanyga. Could you please provide us an example of text and pattern You would like to match?

**Comment by yosmanyga** [comment]
`Subscripción`, to match as `@string@`.

**Comment by norzechowicz** [comment]
Sorry for very late response but I was quite busy in last few months. 
I just checked your case and it works for me. Could you please provide full example of pattern and data u are trying to match?
