### ISSUE TITLE
"OR" operator

### ISSUE THREAD

**Issue by Igreh** [coduo/php-matcher#53]
It will be very useful to have simple "OR" operator.
Ex: check whether value is string or null @string@||@null@ or @string@.or(@null@)
Is there any way to implement it?

And yes, I know I can extend expression language and add my own functions but native implementation is more descriptive, imho

**Comment by norzechowicz** [comment]
``@string@||@null@`` would be awesome, just need to find some time to implement it :P

**Comment by partikus** [comment]
@norzechowicz please look at #74

**Comment by norzechowicz** [comment]
@partikus I have seen that (awesome work!) but I would like first to solve #71. I'm not sure if #74 wont complicate #71 even more.

**Comment by norzechowicz** [comment]
Solved by #74
