### ISSUE TITLE
Array format with trailing comma weird behavior

### ISSUE THREAD

**Issue by ktzouno** [coduo/php-matcher#58]
Hello,

I noticed a weird behavior when the matching pattern contains an array with a trailing comma after the final element as seen in the example and it's output below.

I'd expect the trailing comma to be ignored in the "First" test below and not throw an error.
But take a look at the "Second" test, where the error is incorrectly about the @null@ formatter.

```php
<?php
use Coduo\PHPMatcher\Factory\SimpleFactory;

$factory = new SimpleFactory();
$matcher = $factory->createMatcher();

$match = $matcher->match(
    '{"ids": [1, 2]}',
    '{"ids": [@integer@, @integer@,]}'
);

if (!$match) {
    echo "First: " . $matcher->getError() . "\n";
}

$match = $matcher->match(
    '{"value": null, "ids": [1, 2]}',
    '{"value": @null@, "ids": [@integer@, @integer@,]}'
);

if (!$match) {
    echo "Second: " . $matcher->getError() . "\n";
}
```

Output:
First: "{"ids": [1, 2]}" does not match "{"ids": [@integer@, @integer@,]}" pattern
Second: Type pattern "@null@" is not supported by TextMatcher.

**Comment by norzechowicz** [comment]
First test is failing becaus trailing comma after final element makes this pattern invalid JSON, so json matcher is skipped. Not sure why you expect matcher to fix pattern before matching. 
About second test I agree that error message is non descriptive. I gonna take a look at it as soon as possible.

**Comment by ktzouno** [comment]
I agree it's invalid JSON. It took me quite some time to isolate this issue from a big pattern. Do you think it's easy to display a more descriptive error when JSON validation fails?

**Comment by norzechowicz** [comment]
To be honest I have no idea, need to look into the code to figure that out, I gonna let you know.
