### ISSUE TITLE
2.0.0 Release cycle 

### ISSUE THREAD

**Issue by norzechowicz** [coduo/php-matcher#66]
Version ``2.0.0-alpha1`` was just released. From now on, every monday I will release next version in order to finish with stable release ``2.0.0``

- [x] ``2.0.0-alpha1`` - 25.01.2016
- [x] ``2.0.0-alpha2`` - (will be skipped in case of no changes) - 01.02.2015
- [x] ``2.0.0-beta`` - 08.02.2016 (beta1 and beta2 are merged to beta)
- [x] ``2.0.0-rc``  - 15.02.2016
- [x] ``2.0.0-rc1``  - 03.03.2016 - <s>solved #71</s>
- [x] ``2.0.0-rc2`` - 18.03.2016 - finally solved #71  
- [x] ``2.0.0`` - 25.03.2016

So in the worse scenario I will release stable version ``2.0.0`` on 29.02.2015. But in case of no problems with ``2.0.0-alpha1`` I will skip to beta1 and then to rc1 so ``2.0.0`` can be possibly released on 22.02.2015

**Also from version we are going to follow semantic versioning guidelines.**
[changelog](https://github.com/coduo/php-matcher/blob/master/CHANGELOG.md#200-alpha1) and [upgrade](https://github.com/coduo/php-matcher/blob/master/UPGRADE.md) documents should be from now updated after each PR that require it.

**Comment by norzechowicz** [comment]
Version ``2.0.0-alpha1`` was release today, if you are using php-matcher in your project, please try to update dependencies and let me know if case on any problemts. Thanks!

**Comment by eXtreme** [comment]
It would be cool to bump `phpunit` dependency version to allow 5.x (now `^4.8` is required).

**Comment by norzechowicz** [comment]
Version ``2.0.0-alpha2`` was release today, if you are using php-matcher in your project, please try to update dependencies and let me know if case on any problemts. Thanks!

**Comment by norzechowicz** [comment]
Version ``2.0.0-beta`` (beta1 and beta2 are merged into one release, beta) was release today, if you are using php-matcher in your project, please try to update dependencies and let me know if case on any problemts. Thanks!

**Comment by norzechowicz** [comment]
Because of #71 I had to add extra pre release ``2.0.0-rc1``. Please update your projects and let me know if case of any problems. 
``2.0.0`` stable release is now planned for 07.03.2016

**Comment by lchrusciel** [comment]
Do you know, when you will be able to release stable version?

**Comment by norzechowicz** [comment]
@lchrusciel can you help help with #71 ?

**Comment by lchrusciel** [comment]
I will try to figure something out. Didn't notice that issue.

**Comment by norzechowicz** [comment]
cool, thanks!

**Comment by norzechowicz** [comment]
Thanks to @partikus we finally solved #71 issue. Also OR operator was added ``@string@||@null``, please update your project dependnecies to ``2.0.0-rc2`` and let me in case of any problems, thanks!

**Comment by norzechowicz** [comment]
Finally we did it! Thanks @partikus @blazarecki and everybody else for help with release `2.0.0` :sparkles:
