### ISSUE TITLE
Null value matching problem

### ISSUE THREAD

**Issue by norzechowicz** [coduo/php-matcher#71]
Following pattern:

```
    {
      "username":null,
      "some_data": @string@ 
    }
```

does not match value

```
{"username":null,"some_data":"test"}
```

but when using ``@wildcard@`` or ``@null@`` instead of ``null`` in patter it works. This issue needs to be solved before 2.0.0 release described here #66 

Tested with version ``2.0.0-rc``

**Comment by blazarecki** [comment]
Any new for this issue ?

**Comment by norzechowicz** [comment]
No, feel free to take a closer look on it.

**Comment by blazarecki** [comment]
Good, I'll look tonight.

**Comment by blazarecki** [comment]
I think we have to reopen the issue.

I test the **rc1** on a private project and I have errors. `There is no element under path [mainImage] in pattern.` 

I think I find a solution, I'll create a PR tonight if possible.

**Comment by norzechowicz** [comment]
@blazarecki can you give us more details about your failing example? I tried to reproduce that issue, no luck so far

**Comment by norzechowicz** [comment]
Problem solved, thanks @partikus
