### ISSUE TITLE
Allow Unbounded Array pattern @...@ to match none or more array elements

### ISSUE THREAD

**Issue by ktzouno** [coduo/php-matcher#72]
In the following example the users array should have at least 2 elements for the "@...@" to work currently. How about it works with only one element?

```
'users' => array(
          array(
              'id' => '@integer@.greaterThan(0)',
              'firstName' => '@string@',
              'lastName' => 'Orzechowicz',
              'roles' => '@array@'
          ),
          '@...@'
      ),
```

**Comment by jkobus** [comment]
> There is no element under path [_embedded][items][0][_embedded][authors][1] in value.
:+1:

**Comment by Gamesh** [comment]
@ktzouno made a PR for that, check it out.
@jkobus i thinks that should be raised as a separate issue.
