### ISSUE TITLE
How to use pattern extenders in behat

### ISSUE THREAD

**Issue by mccrodp** [coduo/php-matcher#80]
I am quite confused how to do anything dynamic with JSON at the moment. I've looked at the docs and issue queue but I'm running into limitations.

I want to test for the following where the `result` items can be infinite:

````json
{
          "result": [{
            "id": 2,
            "displayName": "Company Name",
            "dataType": "string",
            "length": 255,
            "rest": {
              "name": "company",
              "readOnly": false
            }
          },
          {
            "id": 3,
            "displayName": "Billing Address",
            "dataType": "text",
            "rest": {
              "name": "billingStreet",
              "readOnly": false
            }
          }],
          "success": true
}
````

I want to do something like so in Behat feature code:

````feature
Then the response should contain json:
    """
    {
      "result": @array@.repeat(
        {
          "id": @integer@,
          "displayName": @string@,
          "dataType": @string@,
          "rest": {
            "name": @string@,
            "readOnly": @string@
          }
        }, 1, INF
      ),
      "success": true
    }
    """
````

I get the error for most extenders: 
> Type pattern "@array@" is not supported by TextMatcher.

How do we do the following in Behat using this library? https://github.com/coduo/php-matcher/issues/21 Thanks.

**Comment by norzechowicz** [comment]
Yea this error message might be confusing :/ Root of the problem is that "repeat" pattern does not exist so actually its not possible to use it.

**Comment by mccrodp** [comment]
Hi,thanks for the fast response. 

Ok. It's more of an ideal method, but is there any other approach using wildcard or similar to match unlimited number for elements as I refer to above?

I've tried a few solutions incl trays which also give the same error. I don't know how to use the pattern extenders in this context in general either and havent seen it used in this way yet in docs or issues / code examples online so I'm not sure how to achieve the goal or if phpmatcher is the right solution. Thanks

**Comment by mccrodp** [comment]
I'm sure there's a better way in the Behat / PHP world (with PHPMatcher). My work around for the moment is the change the test to test only on a specific element:

````feature
Then the response should have success 'true' and element 'result' containing json:
    """
      {
        "id":@integer@,
        "displayName":@string@,
        "dataType":@string@,
        "length":@integer@,
        "rest": {
          "name":@string@,
          "readOnly":false
        }
      }
    """
````

and PHP:

````php
/**
   * @Then the response should have success :arg1 and element :arg2 containing json:
   */
  public function theResponseShouldHaveSuccessAndContainJson($arg1, $arg2, PyStringNode $string) {
    try {
      $expected_value = $string->getRaw();

      // Extract the elements we want to check.
      $response = json_decode($this->client->getLastResponse());
      $data = json_decode($response->data);
      $element = json_encode($data->{$arg2}[0]);
      $success = $data->{'success'};

      $factory = new SimpleFactory();
      $matcher = $factory->createMatcher();
      // Use the pattern matcher to verify JSON.
      if($success == $arg1 && !$matcher->match($element, $expected_value)) {
        $message = sprintf('JSON mismatch: ', $matcher->getError());
        throw new \Exception($message);
      }
    }
    catch (Exception $e) {
      throw new Exception($e->getMessage());
    }
  }
````

Not ideal, so just checking if there was a better documented / undocumented way with PHPMatcher.

**Comment by norzechowicz** [comment]
Unfortunately this is the only solution that I know for now. `repeat` or matcher expander for array would be extremely useful for that case, if you have some free time, help is more than welcome :)

**Comment by mccrodp** [comment]
Thanks again. Unfortunate but good to know I'm not missing something obvious, haha. 

I'd love to help, I'll suggest it in work and see if I can get some time on it. I imagine it's pretty involved though and I've some other open source work in the queue before it ;) I'll update here either way.
