### ISSUE TITLE
The JSON matcher does not seem to be working with regexes.

### ISSUE THREAD

**Issue by robinvdvleuten** [coduo/php-matcher#83]
Hi there,

Currently I try to match the following pattern:

```json
{
  "entries": [
    {
      "id": @string@.matchRegex('/^[a-f0-9]{8}\-[a-f0-9]{4}\-4[a-f0-9]{3}\-(8|9|a|b)[a-f0-9]{3}\-[a-f0-9]{12}$/')
    }
  ]
}
```

But somehow the matcher does not detect the regex correctly.

**Comment by norzechowicz** [comment]
Could you also show us what exactlty are you trying to match with this pattern? Do you have any error or maybe its only not matching?

**Comment by robinvdvleuten** [comment]
It's not matching at all, in this case but also in a more simple regex;

```json
{
  "entries": [
    {
      "id": @string@.matchRegex('/test/')
    }
  ]
}
```

**Comment by norzechowicz** [comment]
Could you please share both, pattern & value? 
https://github.com/coduo/php-matcher/blob/master/tests/MatcherTest.php#L249-L250 this test proves that regex expander works. Maybe there is something wrong with your regex or value?

**Comment by norzechowicz** [comment]
@robinvdvleuten it turns out that this problem is related to JSONMatcher, not regex expander itself. I'm closing this issue since I described everything here https://github.com/coduo/php-matcher/issues/90
