### ISSUE TITLE
Optional JSON fields

### ISSUE THREAD

**Issue by SergeC** [coduo/php-matcher#93]
Is any way to mark a field as optional?

**Comment by norzechowicz** [comment]
@SergeC could you give some examples where optional "field" makes sense?

**Comment by SergeC** [comment]
Here is our use case. We're using JMS serializer http://jmsyst.com/libs/serializer http://jmsyst.com/bundles/JMSSerializerBundle . If an object that is serializing has a field with value "null" it automatically removes it from result JSON. That's why we need to tell php-matcher that certain fields are optional and it shouldn't trigger an error if it does not exist while if it exists it should match given pattern.

**Comment by norzechowicz** [comment]
That make perfect sense, so something similar to `"fieldName":@optional@` would be nice to have? Can you create a pull request with that feature?

**Comment by SergeC** [comment]
> That make perfect sense, so something similar to "fieldName":@optional@ would be nice to have? 

I would suggest use "@integer@.optional()". Because if an optional field is present it must match given pattern (@integer@).

> Can you create a pull request with that feature?

I'll try on next weekend Mar 10-11.

**Comment by trongdung258** [comment]
I need this feature for my project. Hope you update this feature as soon as possible. Thank you!

**Comment by norzechowicz** [comment]
@trongdung258 if you need this feature asap you need to prepare it on your own and send PR, I promise you to review it and merge as soon as possible.

**Comment by trongdung258** [comment]
I'll try and send pull request asap.I think this problem should be resolve.

**Comment by teklakct** [comment]
@SergeC, @trongdung258 I've made some changes in #102. I assume that should resolve your cases
